core config:
  dbuser: homestead
  dbpass: secret
  dbhost: localhost
  extra-php: |
        define( 'WP_DEBUG', true );
        define( 'WP_POST_REVISIONS', 1 );

@mmboth:
  - @mmstage
  - @mmlive

@mmstage:
  ssh: myriadmobile@35.184.184.103:51840/www/myriadmobile_606/public

@mmlive:
  ssh: myriadmobile@35.184.184.103:49142/www/myriadmobile_606/public

@workstage_rsync:
  - rsync -avz myriadmobile@35.184.184.103:51840/www/myriadmobile_606/public/*
